[package]
name = "extended_morton_coder"
version = "0.1.0"
edition = "2021"

[lib]
name = "extended_morton_coder"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.0"
